remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Die vereinigten Staaten von Europa]
description: [Ein Konzept für einen Europäischen Bundesstaat]